import {
  LocationZone,
  RiskPrediction,
  AlertItem,
  FieldReport,
  DashboardSummary,
  PriorityAction,
  RainfallDataPoint,
  IwvTrendDataPoint,
  InstabilityTrendDataPoint,
  RiskTrendDataPoint,
  DataSourceStatus,
  SystemServiceStatus,
  ModelTelemetry,
} from './types';

export const MOCK_LOCATIONS: LocationZone[] = [
  {
    id: 'loc-001',
    name: 'East Khasi Hills (Cherrapunji / Sohra Slopes)',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    latitude: 25.2702,
    longitude: 91.7323,
    elevationM: 1430,
    demSlopeDegrees: 41,
    drainageBasin: 'Shella-Southern Escarpment Catchment',
    terrainRiskNote: 'Funnel-shaped plateau escarpment causing extreme orographic moisture lifting and convective updrafts.',
    cloudburstSusceptibilityScore: 94,
    populationEstimate: 38000,
    nearbyRoads: ['SH-5 (Shillong-Sohra Road)', 'Mawsmai Escarpment Track'],
    nearbyVillages: ['Cherrapunji', 'Mawsmai', 'Nohkalikai Ridge', 'Shella'],
    infrastructureNotes: 'World-record intense precipitation zone with steep sandstone gorges and vulnerable causeways.',
  },
  {
    id: 'loc-002',
    name: 'North Sikkim (Mangan - Chungthang Sector)',
    district: 'North Sikkim',
    state: 'Sikkim',
    latitude: 27.5126,
    longitude: 88.5283,
    elevationM: 2100,
    demSlopeDegrees: 44,
    drainageBasin: 'Upper Teesta River Hydrologic Sub-basin',
    terrainRiskNote: 'Glacial valley choke points susceptible to cloudburst-induced debris flows and sudden river surges.',
    cloudburstSusceptibilityScore: 91,
    populationEstimate: 24000,
    nearbyRoads: ['North Sikkim Highway', 'Chungthang-Lachen Route'],
    nearbyVillages: ['Mangan', 'Chungthang', 'Tung', 'Shipgyer'],
    infrastructureNotes: 'Vulnerable hydro-electric dam reservoirs, staging bridges, and steep mountain passes.',
  },
  {
    id: 'loc-003',
    name: 'Uttarkashi (Bhagirathi River Escarpment)',
    district: 'Uttarkashi',
    state: 'Uttarakhand',
    latitude: 30.7268,
    longitude: 78.4372,
    elevationM: 1352,
    demSlopeDegrees: 39,
    drainageBasin: 'Bhagirathi Upper Himalayan Watershed',
    terrainRiskNote: 'High alpine ridges triggering rapid cloud top cooling and sudden localized cloudburst deluges.',
    cloudburstSusceptibilityScore: 89,
    populationEstimate: 42000,
    nearbyRoads: ['NH-34 (Gangotri Highway)', 'Dharasu Bypass'],
    nearbyVillages: ['Maneri', 'Joshiyara', 'Bhatwari', 'Gangori'],
    infrastructureNotes: 'Gangotri pilgrimage corridor prone to flash inundation and steep riverbed scouring.',
  },
  {
    id: 'loc-004',
    name: 'Mumbai Coastal Plain (Kurla - Mithi River Basin)',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    latitude: 19.0760,
    longitude: 72.8777,
    elevationM: 8,
    demSlopeDegrees: 4,
    drainageBasin: 'Mithi River Estuary & Storm Drain Grid',
    terrainRiskNote: 'Low-elevation coastal estuarine basin prone to high-tide combined urban flash floods.',
    cloudburstSusceptibilityScore: 82,
    populationEstimate: 1200000,
    nearbyRoads: ['Western Express Highway', 'LBS Marg', 'SANTACRUZ-CHEMBUR LINK ROAD'],
    nearbyVillages: ['Kurla', 'Sion', 'Bandra-Kurla Complex', 'Chembur'],
    infrastructureNotes: 'Dense urban commercial hub with tidal waterlogging risk along suburban railway tracks.',
  },
  {
    id: 'loc-005',
    name: 'Guwahati (Brahmaputra Valley & Bharalu Basin)',
    district: 'Kamrup Metropolitan',
    state: 'Assam',
    latitude: 26.1445,
    longitude: 91.7362,
    elevationM: 55,
    demSlopeDegrees: 12,
    drainageBasin: 'Bharalu Stream & Deepor Beel Catchment',
    terrainRiskNote: 'Alluvial valley trough bounded by granite knolls causing localized convective storm stagnation.',
    cloudburstSusceptibilityScore: 78,
    populationEstimate: 950000,
    nearbyRoads: ['GS Road', 'NH-27 Guwahati Bypass', 'Assam Trunk Road'],
    nearbyVillages: ['Dispur', 'Zoo Road', 'Chandmari', 'Jalukbari'],
    infrastructureNotes: 'State capital administrative zone with severe urban street inundation during intense downpours.',
  },
  {
    id: 'loc-006',
    name: 'Delhi-NCR (Yamuna Floodplain & Ridge Zone)',
    district: 'Central Delhi',
    state: 'Delhi',
    latitude: 28.6139,
    longitude: 77.2090,
    elevationM: 216,
    demSlopeDegrees: 3,
    drainageBasin: 'Najafgarh Drain & Yamuna River Floodplain',
    terrainRiskNote: 'Urban heat island effect triggering rapid convective squall lines and localized cell bursts.',
    cloudburstSusceptibilityScore: 74,
    populationEstimate: 2200000,
    nearbyRoads: ['Ring Road', 'Outer Ring Road', 'Delhi-Gurugram Expressway'],
    nearbyVillages: ['ITO', 'Kashmere Gate', 'Minto Bridge', 'Lajpat Nagar'],
    infrastructureNotes: 'Critical national transport corridors and underpasses sensitive to rapid rain rates.',
  },
  {
    id: 'loc-007',
    name: 'Imphal West (Noney - Ijei River Basin)',
    district: 'Noney / Imphal West',
    state: 'Manipur',
    latitude: 24.8170,
    longitude: 93.7258,
    elevationM: 780,
    demSlopeDegrees: 37,
    drainageBasin: 'Ijei River Hydro-Catchment',
    terrainRiskNote: 'V-shaped mountain valley capturing mesoscale convective complexes and flash-flood surges.',
    cloudburstSusceptibilityScore: 86,
    populationEstimate: 28000,
    nearbyRoads: ['NH-37 (Imphal-Jiribam Highway)', 'Tupul Railway Yard Line'],
    nearbyVillages: ['Tupul', 'Marangching', 'Noney Bazaar'],
    infrastructureNotes: 'Northeast Frontier Railway bridge worksites and highway bridges spanning mountain streams.',
  },
  {
    id: 'loc-008',
    name: 'Chennai Coastal Plain (Adyar & Cooum Estuary)',
    district: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0827,
    longitude: 80.2707,
    elevationM: 6,
    demSlopeDegrees: 2,
    drainageBasin: 'Adyar & Cooum River Urban Estuary',
    terrainRiskNote: 'Flat coastal plain vulnerable to cloudburst outflow boundary collisions and slow-moving storms.',
    cloudburstSusceptibilityScore: 80,
    populationEstimate: 1100000,
    nearbyRoads: ['Anna Salai', 'Grand Southern Trunk Road', 'ECR (East Coast Road)'],
    nearbyVillages: ['Velachery', 'Tambaram', 'Guindy', 'Saidapet'],
    infrastructureNotes: 'Low-lying IT corridors and residential sub-basins with acute flash-waterlogging risks.',
  },
];

export const MOCK_PREDICTIONS: RiskPrediction[] = [
  {
    id: 'pred-001',
    locationId: 'loc-001',
    location: 'East Khasi Hills (Cherrapunji / Sohra Slopes)',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    latitude: 25.2702,
    longitude: 91.7323,
    hazardType: 'cloudburst',
    riskScore: 92,
    probability: 0.92,
    riskLevel: 'CRITICAL',
    forecastWindow: 'Next 2 hours',
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    dataFreshness: 'INSAT-3D TIR & MOSDAC (Updated 3m ago)',
    factors: [
      'IWV Surge: 64.2 kg/m² (+18.4 kg/m² in past 30 mins)',
      'Explosive CAPE: 2850 J/kg with eroding CIN (8 J/kg)',
      'Rapid Cloud Top Temp Drop: -12.4°C/15min (Extremely cold convective core -72°C)',
      'Strong Low-Level Convergence: 4.8 × 10⁻⁴ s⁻¹ pushing Bay of Bengal moisture into escarpment',
    ],
    nearbyInfrastructure: ['Shella Highway Causeway', 'Sohra Hydro Gaging Station', 'Nohkalikai Tourism Ridge'],
    nearbyRoads: ['SH-5 (Shillong-Sohra Road)', 'Mawsmai Escarpment Track'],
    nearbyVillages: ['Cherrapunji', 'Mawsmai', 'Nohkalikai Ridge', 'Shella'],
    integratedWaterVaporKgM2: 64.2,
    iwvHourlyTrendKgM2: 18.4,
    capeJkg: 2850,
    cinJkg: 8,
    lowLevelConvergence: 0.00048,
    verticalWindShearMs: 24.5,
    cttDropRateCPerMin: -12.4,
    qpeRainfallRateMmHr: 112.5,
    demSlopeDegrees: 41,
    drainageBasin: 'Shella-Southern Escarpment Catchment',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'IWV Rapid Moisture Accumulation Surge', contributionPct: 38 },
      { factor: 'Rapid Cloud Top Cooling (-12.4°C/15min)', contributionPct: 29 },
      { factor: 'Convective Instability (CAPE 2850 J/kg)', contributionPct: 21 },
      { factor: 'Low-Level Moisture Convergence', contributionPct: 12 },
    ],
  },
  {
    id: 'pred-002',
    locationId: 'loc-002',
    location: 'North Sikkim (Mangan - Chungthang Sector)',
    district: 'North Sikkim',
    state: 'Sikkim',
    latitude: 27.5126,
    longitude: 88.5283,
    hazardType: 'flash_flood',
    riskScore: 88,
    probability: 0.88,
    riskLevel: 'CRITICAL',
    forecastWindow: 'Next 2-4 hours',
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    dataFreshness: 'IMDAA Reanalysis + INSAT-3DR (Updated 8m ago)',
    factors: [
      'Upstream Cloudburst Inundation Discharge (>95 mm/hr satellite QPE)',
      'DEM Flow Accumulation: High funneling ratio into narrow V-shaped Teesta gorge',
      'IWV: 58.6 kg/m² sustained over glacial valley slopes',
      'Vertical Wind Shear: 22.1 m/s organizing convective storm multi-cell',
    ],
    nearbyInfrastructure: ['Chungthang Hydro Dam Staging Yard', 'BRO Base Camp', 'Singhik Bridge'],
    nearbyRoads: ['North Sikkim Highway', 'Chungthang-Lachen Route'],
    nearbyVillages: ['Mangan', 'Chungthang', 'Tung', 'Shipgyer'],
    integratedWaterVaporKgM2: 58.6,
    iwvHourlyTrendKgM2: 12.1,
    capeJkg: 2400,
    cinJkg: 12,
    lowLevelConvergence: 0.00041,
    verticalWindShearMs: 22.1,
    cttDropRateCPerMin: -9.8,
    qpeRainfallRateMmHr: 95.0,
    demSlopeDegrees: 44,
    drainageBasin: 'Upper Teesta River Hydrologic Sub-basin',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'DEM Hydrologic Flow Concentration', contributionPct: 36 },
      { factor: 'Upstream Satellite QPE Intensity (95mm/hr)', contributionPct: 31 },
      { factor: 'Cloud Top Temperature Collapse', contributionPct: 18 },
      { factor: 'Integrated Water Vapor Load', contributionPct: 15 },
    ],
  },
  {
    id: 'pred-003',
    locationId: 'loc-003',
    location: 'Uttarkashi (Bhagirathi River Escarpment)',
    district: 'Uttarkashi',
    state: 'Uttarakhand',
    latitude: 30.7268,
    longitude: 78.4372,
    hazardType: 'cloudburst',
    riskScore: 85,
    probability: 0.85,
    riskLevel: 'CRITICAL',
    forecastWindow: 'Next 3 hours',
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    dataFreshness: 'MOSDAC INSAT-3D + IMDAA (Updated 14m ago)',
    factors: [
      'High IWV Spike: 57.2 kg/m² over high-altitude Himalayan ridge',
      'Orographic forced convective ascent: CTT drop rate -10.5°C/15min',
      'CAPE: 2250 J/kg with zero CIN barrier remaining',
    ],
    nearbyInfrastructure: ['Maneri Bhali Hydro Dam Stage II', 'Gangori Highway Bridge'],
    nearbyRoads: ['NH-34 (Gangotri Highway)', 'Dharasu Bypass'],
    nearbyVillages: ['Maneri', 'Joshiyara', 'Bhatwari', 'Gangori'],
    integratedWaterVaporKgM2: 57.2,
    iwvHourlyTrendKgM2: 14.8,
    capeJkg: 2250,
    cinJkg: 4,
    lowLevelConvergence: 0.00038,
    verticalWindShearMs: 19.8,
    cttDropRateCPerMin: -10.5,
    qpeRainfallRateMmHr: 88.0,
    demSlopeDegrees: 39,
    drainageBasin: 'Bhagirathi Upper Himalayan Watershed',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'Himalayan Orographic IWV Concentration', contributionPct: 40 },
      { factor: 'Cloud Top Temperature Cooling Rate', contributionPct: 30 },
      { factor: 'Thermodynamic Instability (CAPE)', contributionPct: 18 },
      { factor: 'Zero CIN Barrier Erosion', contributionPct: 12 },
    ],
  },
  {
    id: 'pred-004',
    locationId: 'loc-004',
    location: 'Mumbai Coastal Plain (Kurla - Mithi River Basin)',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    latitude: 19.0760,
    longitude: 72.8777,
    hazardType: 'severe_thunderstorm',
    riskScore: 79,
    probability: 0.79,
    riskLevel: 'HIGH',
    forecastWindow: 'Next 3-5 hours',
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    dataFreshness: 'IMDAA Reanalysis (Updated 20m ago)',
    factors: [
      'Mesoscale convective squall line arriving from Arabian Sea',
      'High CAPE: 2600 J/kg with strong low-level wind shear (26.2 m/s)',
      'High IWV: 61.5 kg/m² supporting intense precipitation rate (~70mm/hr)',
    ],
    nearbyInfrastructure: ['Kurla Suburban Rail Junction', 'BKC Commercial Complex', 'Mithi Pumping Station'],
    nearbyRoads: ['Western Express Highway', 'LBS Marg', 'SANTACRUZ-CHEMBUR LINK ROAD'],
    nearbyVillages: ['Kurla', 'Sion', 'Bandra-Kurla Complex', 'Chembur'],
    integratedWaterVaporKgM2: 61.5,
    iwvHourlyTrendKgM2: 9.5,
    capeJkg: 2600,
    cinJkg: 18,
    lowLevelConvergence: 0.00035,
    verticalWindShearMs: 26.2,
    cttDropRateCPerMin: -8.2,
    qpeRainfallRateMmHr: 72.0,
    demSlopeDegrees: 4,
    drainageBasin: 'Mithi River Estuary & Storm Drain Grid',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'Vertical Wind Shear (26.2 m/s)', contributionPct: 35 },
      { factor: 'Convective Energy (CAPE 2600 J/kg)', contributionPct: 32 },
      { factor: 'Integrated Water Vapor Column Load', contributionPct: 20 },
      { factor: 'Low-Level Convergence', contributionPct: 13 },
    ],
  },
  {
    id: 'pred-005',
    locationId: 'loc-005',
    location: 'Guwahati (Brahmaputra Valley & Bharalu Basin)',
    district: 'Kamrup Metropolitan',
    state: 'Assam',
    latitude: 26.1445,
    longitude: 91.7362,
    hazardType: 'flash_flood',
    riskScore: 74,
    probability: 0.74,
    riskLevel: 'HIGH',
    forecastWindow: 'Next 4 hours',
    updatedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    dataFreshness: 'Satellite QPE + CartoDEM (Updated 28m ago)',
    factors: [
      'Localized convective cell producing 65mm/hr rain rate over city bowl',
      'Bharalu stream discharge capacity exceeded; backwater effect from Brahmaputra',
      'IWV: 56.1 kg/m² with low-level convergence peak',
    ],
    nearbyInfrastructure: ['Dispur State Secretariat', 'Guwahati Railway Station', 'Zoo Road Culvert Grid'],
    nearbyRoads: ['GS Road', 'NH-27 Guwahati Bypass', 'Assam Trunk Road'],
    nearbyVillages: ['Dispur', 'Zoo Road', 'Chandmari', 'Jalukbari'],
    integratedWaterVaporKgM2: 56.1,
    iwvHourlyTrendKgM2: 8.2,
    capeJkg: 1950,
    cinJkg: 22,
    lowLevelConvergence: 0.00029,
    verticalWindShearMs: 16.5,
    cttDropRateCPerMin: -6.8,
    qpeRainfallRateMmHr: 65.0,
    demSlopeDegrees: 12,
    drainageBasin: 'Bharalu Stream & Deepor Beel Catchment',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'Satellite QPE Rain Rate (65mm/hr)', contributionPct: 37 },
      { factor: 'DEM Valley Floor Flow Accumulation', contributionPct: 30 },
      { factor: 'IWV Atmospheric Moisture Content', contributionPct: 21 },
      { factor: 'Low-Level Wind Convergence', contributionPct: 12 },
    ],
  },
  {
    id: 'pred-006',
    locationId: 'loc-007',
    location: 'Imphal West (Noney - Ijei River Basin)',
    district: 'Noney / Imphal West',
    state: 'Manipur',
    latitude: 24.8170,
    longitude: 93.7258,
    hazardType: 'flash_flood',
    riskScore: 71,
    probability: 0.71,
    riskLevel: 'HIGH',
    forecastWindow: 'Next 4-6 hours',
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    dataFreshness: 'IMDAA + INSAT-3DR (Updated 35m ago)',
    factors: [
      'Persistent convective precipitation along Ijei river canyon',
      'High DEM slope (37°) directing rapid surface runoff into valley bed',
      'IWV: 53.8 kg/m² with CAPE at 1800 J/kg',
    ],
    nearbyInfrastructure: ['Tupul Railway Yard Yard', 'Bridge No. 164 Substructure'],
    nearbyRoads: ['NH-37 (Imphal-Jiribam Highway)', 'Tupul Railway Yard Line'],
    nearbyVillages: ['Tupul', 'Marangching', 'Noney Bazaar'],
    integratedWaterVaporKgM2: 53.8,
    iwvHourlyTrendKgM2: 6.9,
    capeJkg: 1800,
    cinJkg: 25,
    lowLevelConvergence: 0.00026,
    verticalWindShearMs: 14.8,
    cttDropRateCPerMin: -5.9,
    qpeRainfallRateMmHr: 58.0,
    demSlopeDegrees: 37,
    drainageBasin: 'Ijei River Hydro-Catchment',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'DEM Hydrographic Basin Runoff Routing', contributionPct: 38 },
      { factor: 'Sustained IWV Moisture Feed', contributionPct: 28 },
      { factor: 'QPE Surface Rain Rate', contributionPct: 20 },
      { factor: 'Atmospheric Instability (CAPE)', contributionPct: 14 },
    ],
  },
  {
    id: 'pred-007',
    locationId: 'loc-006',
    location: 'Delhi-NCR (Yamuna Floodplain & Ridge Zone)',
    district: 'Central Delhi',
    state: 'Delhi',
    latitude: 28.6139,
    longitude: 77.2090,
    hazardType: 'severe_thunderstorm',
    riskScore: 62,
    probability: 0.62,
    riskLevel: 'MODERATE',
    forecastWindow: 'Next 3-6 hours',
    updatedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    dataFreshness: 'IMDAA Reanalysis (Updated 42m ago)',
    factors: [
      'Pre-monsoon squall line building over Haryana-Rajasthan border',
      'Moderate CAPE: 1650 J/kg; CIN eroding rapidly from 45 to 15 J/kg',
      'Microburst wind threat (>65 km/h gusts likely)',
    ],
    nearbyInfrastructure: ['Minto Road Underpass', 'ITO Inter-state Bus Terminal', 'Indira Gandhi Airport Runways'],
    nearbyRoads: ['Ring Road', 'Outer Ring Road', 'Delhi-Gurugram Expressway'],
    nearbyVillages: ['ITO', 'Kashmere Gate', 'Minto Bridge', 'Lajpat Nagar'],
    integratedWaterVaporKgM2: 48.2,
    iwvHourlyTrendKgM2: 5.4,
    capeJkg: 1650,
    cinJkg: 15,
    lowLevelConvergence: 0.00022,
    verticalWindShearMs: 18.2,
    cttDropRateCPerMin: -5.2,
    qpeRainfallRateMmHr: 42.0,
    demSlopeDegrees: 3,
    drainageBasin: 'Najafgarh Drain & Yamuna River Floodplain',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'CIN Erosion Rate (45 → 15 J/kg)', contributionPct: 34 },
      { factor: 'Vertical Wind Shear Vector', contributionPct: 29 },
      { factor: 'Unstable CAPE Profile', contributionPct: 22 },
      { factor: 'Low-Level Moisture Feed', contributionPct: 15 },
    ],
  },
  {
    id: 'pred-008',
    locationId: 'loc-008',
    location: 'Chennai Coastal Plain (Adyar & Cooum Estuary)',
    district: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0827,
    longitude: 80.2707,
    hazardType: 'severe_thunderstorm',
    riskScore: 54,
    probability: 0.54,
    riskLevel: 'MODERATE',
    forecastWindow: 'Next 4-6 hours',
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    dataFreshness: 'INSAT-3D TIR (Updated 50m ago)',
    factors: [
      'Sea-breeze front boundary collision triggering isolated cell updrafts',
      'Moderate IWV: 51.4 kg/m²; CAPE: 1400 J/kg',
      'Potential localized high rain rate over eastern IT corridor',
    ],
    nearbyInfrastructure: ['Velachery Flyover Canal', 'Chennai Central Station', 'Adyar River Estuary'],
    nearbyRoads: ['Anna Salai', 'Grand Southern Trunk Road', 'ECR (East Coast Road)'],
    nearbyVillages: ['Velachery', 'Tambaram', 'Guindy', 'Saidapet'],
    integratedWaterVaporKgM2: 51.4,
    iwvHourlyTrendKgM2: 4.1,
    capeJkg: 1400,
    cinJkg: 28,
    lowLevelConvergence: 0.00018,
    verticalWindShearMs: 12.4,
    cttDropRateCPerMin: -4.1,
    qpeRainfallRateMmHr: 35.0,
    demSlopeDegrees: 2,
    drainageBasin: 'Adyar & Cooum River Urban Estuary',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    xaiTopDrivers: [
      { factor: 'Sea-Breeze Convergence Boundary', contributionPct: 38 },
      { factor: 'Integrated Water Vapor Load', contributionPct: 30 },
      { factor: 'Thermodynamic Instability (CAPE)', contributionPct: 20 },
      { factor: 'Vertical Shear Alignment', contributionPct: 12 },
    ],
  },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: 'alt-001',
    predictionId: 'pred-001',
    severity: 'CRITICAL',
    title: 'CRITICAL CLOUDBURST WARNING: Extreme Convective Surge (>110mm/hr)',
    location: 'East Khasi Hills (Cherrapunji / Sohra Slopes)',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    locationId: 'loc-001',
    hazardType: 'cloudburst',
    riskScore: 92,
    probability: 0.92,
    forecastWindow: 'Next 2 hours',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    factors: [
      'IWV Rapid Surge: 64.2 kg/m² (+18.4 kg/m² in 30 mins)',
      'Extreme CAPE (2850 J/kg) with CIN barrier completely eroded',
      'Rapid Cloud Top Temperature Drop: -12.4°C/15min reaching -72°C core',
    ],
    recommendedAction: 'Issue immediate emergency warning sirens for low-lying Shella causeway and waterfall gorges. Pre-position SDRF water rescue teams. Halt all tourist transit on SH-5 Shillong-Sohra route.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'State Disaster Management Authority (SDMA), East Khasi Hills DEOC, SDRF, Tourism Police',
    isSimulated: false,
    simulationVariables: {
      integratedWaterVaporKgM2: 64.2,
      capeJkg: 2850,
      cinJkg: 8,
      lowLevelConvergence: 0.00048,
      verticalWindShearMs: 24.5,
      cttDropRateCPerMin: -12.4,
    },
  },
  {
    id: 'alt-002',
    predictionId: 'pred-002',
    severity: 'CRITICAL',
    title: 'CRITICAL FLASH FLOOD RED ALERT: Teesta River Surge Imminent',
    location: 'North Sikkim (Mangan - Chungthang Sector)',
    district: 'North Sikkim',
    state: 'Sikkim',
    locationId: 'loc-002',
    hazardType: 'flash_flood',
    riskScore: 88,
    probability: 0.88,
    forecastWindow: 'Next 2-4 hours',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    factors: [
      'Upstream Satellite QPE Cloudburst Inundation (>95 mm/hr rain rate)',
      'DEM Flow Accumulation models acute surge in narrow Chungthang canyon',
      'Glacial tributary runoff combining with heavy convective downpour',
    ],
    recommendedAction: 'Evacuate low-lying labor colonies near Chungthang dam. Alert BRO Project Swastik to clear machinery from riverbed. Sound riverbank warning sirens along Mangan-Singhik stretch.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'North Sikkim Collectorate, BRO Swastik, Army Staging Units, NDMA Sachet CAP',
    isSimulated: false,
    simulationVariables: {
      integratedWaterVaporKgM2: 58.6,
      capeJkg: 2400,
      cinJkg: 12,
      lowLevelConvergence: 0.00041,
      verticalWindShearMs: 22.1,
      cttDropRateCPerMin: -9.8,
    },
  },
  {
    id: 'alt-003',
    predictionId: 'pred-003',
    severity: 'CRITICAL',
    title: 'HIGH CLOUDBURST THREAT: Bhagirathi Catchment Deluge',
    location: 'Uttarkashi (Bhagirathi River Escarpment)',
    district: 'Uttarkashi',
    state: 'Uttarakhand',
    locationId: 'loc-003',
    hazardType: 'cloudburst',
    riskScore: 85,
    probability: 0.85,
    forecastWindow: 'Next 3 hours',
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    factors: [
      'IWV spike to 57.2 kg/m² over Bhagirathi high-altitude ridges',
      'Rapid convective cloud top cooling (-10.5°C/15min)',
      'High terrain slope accelerating immediate surface runoff into Gangori',
    ],
    recommendedAction: 'Halt Gangotri pilgrim traffic at Dharasu check-post. Pre-position NDRF teams at Uttarkashi HQ. Issue flood watch for Maneri hydro dam staging zones.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'Uttarkashi DDMA, Uttarakhand State Emergency Operations Centre (SEOC), NDRF',
    isSimulated: false,
  },
  {
    id: 'alt-004',
    predictionId: 'pred-004',
    severity: 'WARNING',
    title: 'SEVERE THUNDERSTORM & SQUALL WARNING: Arabian Sea Squall Line',
    location: 'Mumbai Coastal Plain (Kurla - Mithi River Basin)',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    locationId: 'loc-004',
    hazardType: 'severe_thunderstorm',
    riskScore: 79,
    probability: 0.79,
    forecastWindow: 'Next 3-5 hours',
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    status: 'ACKNOWLEDGED',
    acknowledgedBy: 'Duty Officer V. Patil (MCGM Disaster Cell)',
    acknowledgedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    factors: [
      'CAPE exceeding 2600 J/kg with strong vertical wind shear (26.2 m/s)',
      'Sustained IWV load of 61.5 kg/m² driving heavy rain rates (~70mm/hr)',
      'Risk of urban waterlogging at Kurla rail tracks and LBS Marg underpasses',
    ],
    recommendedAction: 'Activate high-capacity dewatering pumps at Mithi river gates. Alert Central Railway for track water level monitoring. Advise commuters to avoid low-lying underpasses.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'MCGM Disaster Management Cell, Mumbai Traffic Police, Railway Operations',
  },
  {
    id: 'alt-005',
    predictionId: 'pred-005',
    severity: 'WARNING',
    title: 'FLASH FLOOD ADVISORY: Bharalu Stream & Guwahati City Inundation',
    location: 'Guwahati (Brahmaputra Valley & Bharalu Basin)',
    district: 'Kamrup Metropolitan',
    state: 'Assam',
    locationId: 'loc-005',
    hazardType: 'flash_flood',
    riskScore: 74,
    probability: 0.74,
    forecastWindow: 'Next 4 hours',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    factors: [
      'Localized convective rain rate of 65mm/hr over urban valley bowl',
      'DEM drainage model indicates overflow along GS Road and Zoo Road culverts',
    ],
    recommendedAction: 'Open sluice gates at Bharalu mouth. Dispatch Guwahati Municipal Corporation rapid response teams with mobile pump sets.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'Kamrup Metro DDMA, GMC Municipal Cell, Assam State Disaster Management Authority',
  },
  {
    id: 'alt-006',
    predictionId: 'pred-006',
    severity: 'WARNING',
    title: 'FLASH FLOOD ADVISORY: Ijei River Basin High Runoff',
    location: 'Imphal West (Noney - Ijei River Basin)',
    district: 'Noney / Imphal West',
    state: 'Manipur',
    locationId: 'loc-007',
    hazardType: 'flash_flood',
    riskScore: 71,
    probability: 0.71,
    forecastWindow: 'Next 4-6 hours',
    createdAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    factors: [
      'High terrain slope (37°) directing surface runoff into Ijei river canyon',
      'IWV sustained at 53.8 kg/m² with active storm cells',
    ],
    recommendedAction: 'Alert NFR construction engineers at Tupul railway yard. Pre-position rescue inflatable boats at Noney HQ.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'Noney District Administration, Northeast Frontier Railway (NFR), Manipur SDMA',
  },
  {
    id: 'alt-007',
    predictionId: 'pred-007',
    severity: 'WATCH',
    title: 'SEVERE THUNDERSTORM WATCH: Delhi-NCR Squall Line Approach',
    location: 'Delhi-NCR (Yamuna Floodplain & Ridge Zone)',
    district: 'Central Delhi',
    state: 'Delhi',
    locationId: 'loc-006',
    hazardType: 'severe_thunderstorm',
    riskScore: 62,
    probability: 0.62,
    forecastWindow: 'Next 3-6 hours',
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    factors: [
      'CIN barrier eroding from 45 to 15 J/kg ahead of squall line',
      'Microburst wind gusts (>65 km/h) and moderate rainfall rates (42mm/hr)',
    ],
    recommendedAction: 'Issue airport advisory for flight holding patterns. Alert Delhi Traffic Police to monitor Minto Bridge underpass.',
    modelVersion: 'MEGH-MTL-Transformer-v2.4',
    recipientGroup: 'Delhi Disaster Management Authority (DDMA), Traffic Police, Airport Authority',
  },
];

export const MOCK_REPORTS: FieldReport[] = [
  {
    id: 'rep-001',
    reportType: 'heavy_rainfall',
    title: 'Torrential downpour exceeding 100mm/hr in Sohra Bazaar',
    location: 'Sohra Market Square, Cherrapunji',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    latitude: 25.2750,
    longitude: 91.7300,
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    description: 'Visibility under 10 meters due to intense sheet rainfall. Water depth on main road at 1.5 feet and rising fast.',
    mediaUrl: 'https://picsum.photos/seed/sohra_rain/640/420',
    reporterType: 'field_official',
    reporterName: 'Wanlang Khongjee (Sub-Divisional Officer)',
    reporterPhone: '+91 98560-XXXXX',
    verificationStatus: 'pending',
    aiAdvisoryAnalysis: 'Advisory: High correlation with satellite QPE cloudburst spike (112mm/hr). Extreme flash inundation expected down-gradient.',
    roadAffected: 'SH-5 Shillong-Sohra Highway',
    hazardObserved: 'cloudburst',
    rainfallEstimateMm: 110,
    hailObserved: false,
  },
  {
    id: 'rep-002',
    reportType: 'flash_flood',
    title: 'River surge threatening Chungthang bridge staging yard',
    location: 'Chungthang Hydro Power Sub-station',
    district: 'North Sikkim',
    state: 'Sikkim',
    latitude: 27.6015,
    longitude: 88.6472,
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    description: 'Teesta water level has risen 2.5 meters in 20 minutes. Log debris choke forming upstream at Singhik.',
    mediaUrl: 'https://picsum.photos/seed/sikkim_surge/640/420',
    reporterType: 'ndrf_sdrf_team',
    reporterName: 'Sub-Inspector Karma Bhutia (Sikkim SDRF)',
    reporterPhone: '+91 97330-XXXXX',
    verificationStatus: 'verified',
    verifiedBy: 'Mangan District Collector',
    verifiedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    aiAdvisoryAnalysis: 'Advisory: Hydrodynamic DEM routing confirms critical riverbank overflow capacity exceeded.',
    roadAffected: 'North Sikkim Highway',
    hazardObserved: 'flash_flood',
    rainfallEstimateMm: 85,
  },
  {
    id: 'rep-003',
    reportType: 'waterlogging',
    title: 'Suburban rail track submerged at Kurla station',
    location: 'Kurla West Railway Track 3 & 4',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    latitude: 19.0650,
    longitude: 72.8790,
    timestamp: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    description: 'Water accumulation above 8 inches over rail line following 45 minutes of heavy convective thunderstorm.',
    mediaUrl: 'https://picsum.photos/seed/kurla_waterlogging/640/420',
    reporterType: 'traffic_police',
    reporterName: 'Inspector V. Patil (Mumbai Traffic Division)',
    reporterPhone: '+91 98200-XXXXX',
    verificationStatus: 'verified',
    verifiedBy: 'MCGM Emergency Cell Control',
    verifiedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    aiAdvisoryAnalysis: 'Advisory: High tide combined with 72mm/hr storm outflow causing slow drain discharge into Mithi river.',
    roadAffected: 'LBS Marg Kurla Junction',
    hazardObserved: 'severe_thunderstorm',
    rainfallEstimateMm: 65,
  },
  {
    id: 'rep-004',
    reportType: 'hailstorm',
    title: 'Golf-ball sized hail damaging crops and glass roofs in Bhatwari',
    location: 'Bhatwari Apple Orchards, Uttarkashi',
    district: 'Uttarkashi',
    state: 'Uttarakhand',
    latitude: 30.7500,
    longitude: 78.4800,
    timestamp: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    description: 'Severe hailstorm lasting 18 minutes. Large hailstones damaged vehicle windshields and local greenhouse structures.',
    mediaUrl: 'https://picsum.photos/seed/hailstorm_uttarakhand/640/420',
    reporterType: 'citizen',
    reporterName: 'Devendra Rawat',
    verificationStatus: 'verified',
    verifiedBy: 'Uttarkashi Revenue Officer',
    verifiedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    aiAdvisoryAnalysis: 'Advisory: Matches cloud top temperature drop (-10.5°C/15min) indicative of strong convective updraft capable of sustaining large hail.',
    hazardObserved: 'severe_thunderstorm',
    hailObserved: true,
  },
  {
    id: 'rep-005',
    reportType: 'waterlogging',
    title: 'Minto Bridge underpass flooded; vehicle traffic suspended',
    location: 'Minto Road Railway Bridge Underpass',
    district: 'Central Delhi',
    state: 'Delhi',
    latitude: 28.6330,
    longitude: 77.2250,
    timestamp: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    description: '3 feet of water accumulated under the railway bridge. Auto-rickshaw submerged; automatic pump active.',
    mediaUrl: 'https://picsum.photos/seed/minto_bridge/640/420',
    reporterType: 'field_official',
    reporterName: 'Rajesh Sharma (PWD Assistant Engineer)',
    verificationStatus: 'verified',
    verifiedBy: 'DDMA Control Room Officer',
    verifiedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    roadAffected: 'Deen Dayal Upadhyaya Marg',
    hazardObserved: 'severe_thunderstorm',
    rainfallEstimateMm: 45,
  },
];

export const MOCK_RAINFALL_TREND: RainfallDataPoint[] = [
  { time: '00:00', observedMm: 2.1, forecastMm: 2.5, thresholdMm: 50 },
  { time: '04:00', observedMm: 4.8, forecastMm: 5.2, thresholdMm: 50 },
  { time: '08:00', observedMm: 12.4, forecastMm: 14.0, thresholdMm: 50 },
  { time: '12:00', observedMm: 38.6, forecastMm: 42.0, thresholdMm: 50 },
  { time: '16:00', observedMm: 95.2, forecastMm: 105.0, thresholdMm: 50 },
  { time: '20:00', observedMm: 68.4, forecastMm: 72.0, thresholdMm: 50 },
  { time: 'Now', observedMm: 112.5, forecastMm: 120.0, thresholdMm: 50 },
  { time: '+1h (F)', observedMm: 0, forecastMm: 98.4, thresholdMm: 50 },
  { time: '+2h (F)', observedMm: 0, forecastMm: 65.2, thresholdMm: 50 },
  { time: '+3h (F)', observedMm: 0, forecastMm: 32.1, thresholdMm: 50 },
  { time: '+4h (F)', observedMm: 0, forecastMm: 15.0, thresholdMm: 50 },
  { time: '+6h (F)', observedMm: 0, forecastMm: 5.2, thresholdMm: 50 },
];

export const MOCK_IWV_TREND: IwvTrendDataPoint[] = [
  { time: 'T-6h', observedIwvKgM2: 38.2, forecastIwvKgM2: 39.0, thresholdKgM2: 55.0 },
  { time: 'T-4h', observedIwvKgM2: 42.5, forecastIwvKgM2: 43.1, thresholdKgM2: 55.0 },
  { time: 'T-2h', observedIwvKgM2: 49.8, forecastIwvKgM2: 51.0, thresholdKgM2: 55.0 },
  { time: 'T-1h', observedIwvKgM2: 56.4, forecastIwvKgM2: 57.2, thresholdKgM2: 55.0 },
  { time: 'Current', observedIwvKgM2: 64.2, forecastIwvKgM2: 65.0, thresholdKgM2: 55.0 },
  { time: '+1h (F)', observedIwvKgM2: 0, forecastIwvKgM2: 62.1, thresholdKgM2: 55.0 },
  { time: '+2h (F)', observedIwvKgM2: 0, forecastIwvKgM2: 54.8, thresholdKgM2: 55.0 },
  { time: '+4h (F)', observedIwvKgM2: 0, forecastIwvKgM2: 45.2, thresholdKgM2: 55.0 },
];

export const MOCK_INSTABILITY_TREND: InstabilityTrendDataPoint[] = [
  { time: 'T-6h', capeJkg: 850, cinJkg: 140, criticalCapeThreshold: 2000 },
  { time: 'T-4h', capeJkg: 1450, cinJkg: 95, criticalCapeThreshold: 2000 },
  { time: 'T-2h', capeJkg: 2100, cinJkg: 42, criticalCapeThreshold: 2000 },
  { time: 'T-1h', capeJkg: 2600, cinJkg: 18, criticalCapeThreshold: 2000 },
  { time: 'Current', capeJkg: 2850, cinJkg: 8, criticalCapeThreshold: 2000 },
  { time: '+1h (F)', capeJkg: 2450, cinJkg: 25, criticalCapeThreshold: 2000 },
  { time: '+2h (F)', capeJkg: 1800, cinJkg: 65, criticalCapeThreshold: 2000 },
];

export const MOCK_RISK_TREND: RiskTrendDataPoint[] = [
  { time: 'T-6h', averageRisk: 32, peakRisk: 48, threshold: 75 },
  { time: 'T-4h', averageRisk: 46, peakRisk: 62, threshold: 75 },
  { time: 'T-2h', averageRisk: 68, peakRisk: 84, threshold: 75 },
  { time: 'Current', averageRisk: 79, peakRisk: 92, threshold: 75 },
  { time: '+2h (F)', averageRisk: 74, peakRisk: 88, threshold: 75 },
  { time: '+4h (F)', averageRisk: 58, peakRisk: 71, threshold: 75 },
  { time: '+6h (F)', averageRisk: 39, peakRisk: 52, threshold: 75 },
];

export const MOCK_DATA_SOURCES: DataSourceStatus[] = [
  {
    id: 'src-001',
    name: 'IMDAA Reanalysis Grid (NCMRWF / IMD)',
    provider: 'NCMRWF / IMD',
    type: 'reanalysis',
    status: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    latencyMs: 145,
    frequency: 'Hourly Update (12 km native resolution)',
    isSimulated: false,
  },
  {
    id: 'src-002',
    name: 'INSAT-3D / 3DR Satellite Telemetry (MOSDAC)',
    provider: 'ISRO MOSDAC',
    type: 'satellite',
    status: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    latencyMs: 82,
    frequency: '15-Minute Scan (TIR & WV Channels)',
    isSimulated: false,
  },
  {
    id: 'src-003',
    name: 'Satellite Quantitative Precipitation Estimation (QPE)',
    provider: 'IMD / INSAT-3D Blended',
    type: 'precipitation',
    status: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    latencyMs: 110,
    frequency: '15-Minute Rain-Rate Rasters (mm/hr)',
    isSimulated: false,
  },
  {
    id: 'src-004',
    name: 'CartoDEM / SRTM 30m Hydrographic Elevation Model',
    provider: 'ISRO ISRO / USGS DEM',
    type: 'elevation',
    status: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 3600 * 1000).toISOString(),
    latencyMs: 18,
    frequency: 'Static High-Resolution Hydro-Grid',
    isSimulated: false,
  },
  {
    id: 'src-005',
    name: 'IMD Automatic Weather Station (AWS) Ground Network',
    provider: 'India Meteorological Department (IMD)',
    type: 'station',
    status: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    latencyMs: 210,
    frequency: '15-Minute Telemetry Feed',
    isSimulated: false,
  },
];

export const MOCK_SYSTEM_SERVICES: SystemServiceStatus[] = [
  {
    id: 'srv-001',
    name: 'Multi-Task Spatiotemporal Transformer Nowcast Inference Engine',
    status: 'operational',
    uptimePct: 99.94,
    latencyMs: 124,
    version: 'MEGH-MTL-v2.4',
    notes: 'GPU inference cluster active with 2-6h lead-time outputs.',
  },
  {
    id: 'srv-002',
    name: 'MOSDAC Satellite Telemetry Ingestion Receiver',
    status: 'operational',
    uptimePct: 99.98,
    latencyMs: 45,
    version: 'v1.8.2',
    notes: '15-min INSAT-3D TIR/WV frame parser.',
  },
  {
    id: 'srv-003',
    name: 'Explainable AI (XAI) Attribution Module',
    status: 'operational',
    uptimePct: 99.91,
    latencyMs: 68,
    version: 'v1.2.0',
    notes: 'Integrated Gradients feature weight calculator.',
  },
  {
    id: 'srv-004',
    name: 'NDMA Sachet OASIS CAP Alert Gateway',
    status: 'operational',
    uptimePct: 100.0,
    latencyMs: 38,
    version: 'CAP-v1.2-Proxy',
    notes: 'Common Alerting Protocol XML parser & SMS dispatcher.',
  },
];

export const MOCK_MODEL_TELEMETRY: ModelTelemetry = {
  activeModel: 'Spatiotemporal Multi-Task Learning (MTL) Transformer',
  modelVersion: 'MEGH-MTL-v2.4',
  hazardType: 'multi-task: severe_thunderstorm + cloudburst + flash_flood',
  trainedAt: '2026-08-15 (Trained on 10 years IMDAA + INSAT-3D corpus)',
  trainingPeriod: '2016 - 2026 (Monsoon & Pre-monsoon severe weather events)',
  trainingDatasetSize: '4.8 TB spatiotemporal raster cubes',
  precision: 0.914,
  recall: 0.942,
  f1Score: 0.928,
  aucRoc: 0.965,
  inferenceLatencyMs: 124,
  topFeatures: [
    { name: 'Integrated Water Vapor (IWV) Column Surge', importance: 0.36 },
    { name: 'Cloud Top Temperature (CTT) Drop Rate', importance: 0.28 },
    { name: 'Convective Available Potential Energy (CAPE)', importance: 0.18 },
    { name: 'DEM Hydrographic Flow Accumulation', importance: 0.10 },
    { name: 'Low-Level Wind Convergence', importance: 0.05 },
    { name: 'Vertical Wind Shear (0-6km)', importance: 0.03 },
  ],
  perHeadMetrics: [
    {
      hazard: 'cloudburst',
      precision: 0.925,
      recall: 0.951,
      f1Score: 0.938,
      leadTimeHoursMedian: 2.8,
    },
    {
      hazard: 'flash_flood',
      precision: 0.908,
      recall: 0.936,
      f1Score: 0.922,
      leadTimeHoursMedian: 3.5,
    },
    {
      hazard: 'severe_thunderstorm',
      precision: 0.910,
      recall: 0.940,
      f1Score: 0.925,
      leadTimeHoursMedian: 4.2,
    },
  ],
};

export const MOCK_PRIORITY_ACTIONS: PriorityAction[] = [
  {
    id: 'act-001',
    severity: 'CRITICAL',
    title: 'IMMEDIATE CLOUDBURST SIREN & CAUSEWAY EVACUATION',
    location: 'East Khasi Hills (Cherrapunji / Sohra Slopes)',
    timeContext: 'Immediate Window (Next 1-2 Hours)',
    actionRequired: 'Sound emergency sirens for Shella causeway settlements. Dispatch SDRF water rescue alpha unit. Close SH-5 tourist access points.',
    assignedUnit: 'East Khasi Hills DDMA & Meghalaya SDRF Alpha',
    status: 'dispatched',
  },
  {
    id: 'act-002',
    severity: 'CRITICAL',
    title: 'TEESTA RIVER SURGE RED ALERT & DAM STAGING CLEARANCE',
    location: 'North Sikkim (Mangan - Chungthang Sector)',
    timeContext: 'Immediate Window (Next 2 Hours)',
    actionRequired: 'Halt all construction at Chungthang hydro dam staging yard. Pre-position BRO heavy earth-movers at Singhik bridge.',
    assignedUnit: 'North Sikkim Collectorate & BRO Project Swastik',
    status: 'in_progress',
  },
  {
    id: 'act-003',
    severity: 'CRITICAL',
    title: 'BHAGIRATHI CATCHMENT FLOOD WATCH & PILGRIM TRAFFIC HALT',
    location: 'Uttarkashi (Bhagirathi River Corridor)',
    timeContext: 'Next 2-3 Hours',
    actionRequired: 'Halt Gangotri pilgrim vehicles at Dharasu bypass. Alert Maneri hydro dam operators to manage sluice gates.',
    assignedUnit: 'Uttarkashi District Police & NDRF Team 4',
    status: 'dispatched',
  },
  {
    id: 'act-004',
    severity: 'HIGH',
    title: 'ACTIVATE MITHI RIVER PUMPING STATIONS & KURLA RAIL MONITORING',
    location: 'Mumbai Suburban (Kurla - LBS Marg Junction)',
    timeContext: 'Next 3-5 Hours',
    actionRequired: 'Open Mithi storm gates ahead of high tide. Standby dewatering diesel pump trucks at Kurla West subway.',
    assignedUnit: 'MCGM Stormwater Cell & Central Railway Engineering',
    status: 'in_progress',
  },
];
