'use client';

import React from 'react';
import { AlertItem } from '@/lib/types';
import { X, MapPin, AlertTriangle, ShieldCheck, CheckCircle2, Clock, Check, Sparkles, Cpu, Sliders } from 'lucide-react';

interface AlertDetailModalProps {
  alert: AlertItem | null;
  onClose: () => void;
  onAcknowledge: (alertId: string) => void;
  onResolve: (alertId: string) => void;
  onViewOnMap: (locationId: string) => void;
}

export default function AlertDetailModal({
  alert,
  onClose,
  onAcknowledge,
  onResolve,
  onViewOnMap,
}: AlertDetailModalProps) {
  if (!alert) return null;

  const getSeverityBadge = (severity: string, isSimulated?: boolean) => {
    if (isSimulated) {
      return 'bg-purple-100 text-purple-800 border-purple-300';
    }
    switch (severity) {
      case 'CRITICAL':
        return 'bg-red-100 text-red-800 border-red-300';
      case 'WARNING':
        return 'bg-orange-100 text-orange-800 border-orange-300';
      case 'WATCH':
        return 'bg-amber-100 text-amber-800 border-amber-300';
      default:
        return 'bg-blue-100 text-blue-800 border-blue-300';
    }
  };

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-2xs">
      <div
        id="alert-detail-modal"
        className={`bg-white rounded-md border shadow-xl max-w-2xl w-full max-h-[90vh] flex flex-col text-slate-800 animate-in fade-in zoom-in-95 duration-150 ${
          alert.isSimulated ? 'border-purple-300' : 'border-slate-200'
        }`}
      >
        {/* Header */}
        <div className={`p-4 border-b flex items-start justify-between ${
          alert.isSimulated ? 'bg-purple-50/50 border-purple-200' : 'border-slate-100'
        }`}>
          <div>
            <div className="flex flex-wrap items-center gap-1.5 mb-1">
              {alert.isSimulated ? (
                <span className="inline-flex items-center space-x-1 text-[10px] font-bold px-2 py-0.5 rounded bg-purple-100 text-purple-900 border border-purple-300 tracking-wide uppercase">
                  <Sparkles className="w-3 h-3 text-purple-700" />
                  <span>AI SIMULATION DRILL</span>
                </span>
              ) : (
                <span className="inline-flex items-center text-[10px] font-semibold px-1.5 py-0.5 rounded bg-purple-50 text-purple-800 border border-purple-200">
                  📡 MOSDAC & IMDAA Live Telemetry
                </span>
              )}

              <span
                className={`text-xs font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${getSeverityBadge(
                  alert.severity,
                  alert.isSimulated
                )}`}
              >
                {alert.severity}
              </span>
              <span className="text-xs uppercase font-bold bg-purple-100 text-purple-900 px-2 py-0.5 rounded">
                {alert.hazardType.replace('_', ' ')}
              </span>
              <span className="text-xs text-slate-500 font-mono">
                ID: {alert.id}
              </span>
              <span className="text-xs px-2 py-0.5 rounded-full font-semibold bg-slate-100 text-slate-800">
                Status: {alert.status}
              </span>
            </div>
            <h2 className="text-base font-bold text-slate-900">{alert.title}</h2>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 p-1.5 rounded hover:bg-slate-100"
            title="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body content */}
        <div className="p-4 overflow-y-auto space-y-4 text-xs">
          {/* Simulated Alert Banner */}
          {alert.isSimulated && (
            <div className="bg-purple-50 border-2 border-purple-300 rounded-md p-3 text-purple-950 flex items-start space-x-2.5">
              <Cpu className="w-5 h-5 text-purple-700 shrink-0 mt-0.5" />
              <div>
                <strong className="text-xs font-bold text-purple-900 block uppercase tracking-wide">
                  ⚠️ AI NOWCAST SIMULATION DRILL ALERT
                </strong>
                <p className="text-[11px] text-purple-800 mt-0.5 leading-relaxed">
                  Generated by the <strong>MEGH-AI Multi-Task Spatiotemporal Transformer (MEGH-MTL-v2.4)</strong> for nowcast lead-time verification and emergency response drills.
                </p>
              </div>
            </div>
          )}

          {/* Geolocation & Target Summary */}
          <div className="bg-slate-50 p-3 rounded border border-slate-200 grid grid-cols-2 sm:grid-cols-4 gap-2.5">
            <div>
              <span className="text-slate-500 block text-[11px]">Station / Location</span>
              <span className="font-semibold text-slate-800 flex items-center">
                <MapPin className="w-3 h-3 mr-1 text-purple-600 shrink-0" />
                {alert.district}
              </span>
            </div>
            <div>
              <span className="text-slate-500 block text-[11px]">Risk Score</span>
              <span className="font-semibold text-slate-800 font-mono">
                {alert.riskScore}/100 ({Math.round(alert.probability * 100)}%)
              </span>
            </div>
            <div>
              <span className="text-slate-500 block text-[11px]">Lead Time Window</span>
              <span className="font-semibold text-purple-900 font-mono">{alert.forecastWindow}</span>
            </div>
            <div>
              <span className="text-slate-500 block text-[11px]">Model Engine</span>
              <span className="font-mono text-slate-700 text-[11px]">{alert.modelVersion}</span>
            </div>
          </div>

          {/* Simulation variables */}
          {alert.simulationVariables && (
            <div className="bg-slate-50 p-3 rounded border border-slate-200">
              <span className="text-[11px] font-bold text-slate-800 flex items-center mb-2 space-x-1">
                <Sliders className="w-3.5 h-3.5 text-purple-600 mr-1" />
                <span>Atmospheric & Satellite Predictor Telemetry:</span>
              </span>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-[11px] font-mono">
                <div className="bg-white p-2 rounded border border-slate-200">
                  <span className="text-slate-500 block text-[10px]">IWV Moisture</span>
                  <span className="font-bold text-blue-700">{alert.simulationVariables.integratedWaterVaporKgM2} kg/m²</span>
                </div>
                <div className="bg-white p-2 rounded border border-slate-200">
                  <span className="text-slate-500 block text-[10px]">CAPE Instability</span>
                  <span className="font-bold text-amber-700">{alert.simulationVariables.capeJkg} J/kg</span>
                </div>
                <div className="bg-white p-2 rounded border border-slate-200">
                  <span className="text-slate-500 block text-[10px]">CIN Barrier</span>
                  <span className="font-bold text-slate-800">{alert.simulationVariables.cinJkg} J/kg</span>
                </div>
                <div className="bg-white p-2 rounded border border-slate-200">
                  <span className="text-slate-500 block text-[10px]">CTT Cooling Rate</span>
                  <span className="font-bold text-purple-700">{alert.simulationVariables.cttDropRateCPerMin} °C/min</span>
                </div>
                <div className="bg-white p-2 rounded border border-slate-200">
                  <span className="text-slate-500 block text-[10px]">0-6km Shear</span>
                  <span className="font-bold text-indigo-700">{alert.simulationVariables.verticalWindShearMs} m/s</span>
                </div>
                <div className="bg-white p-2 rounded border border-slate-200">
                  <span className="text-slate-500 block text-[10px]">Convergence</span>
                  <span className="font-bold text-slate-700">{((alert.simulationVariables.lowLevelConvergence ?? 0) * 10000).toFixed(1)} × 10⁻⁴ s⁻¹</span>
                </div>
              </div>
            </div>
          )}

          {/* Timestamps */}
          <div className="flex flex-wrap items-center gap-4 text-slate-500 text-[11px] border-b border-slate-100 pb-3">
            <span className="flex items-center">
              <Clock className="w-3.5 h-3.5 mr-1 text-slate-400" />
              Created: <strong>{new Date(alert.createdAt).toLocaleString()} IST</strong>
            </span>
            <span className="flex items-center">
              <Clock className="w-3.5 h-3.5 mr-1 text-slate-400" />
              Last Updated: <strong>{new Date(alert.updatedAt).toLocaleString()} IST</strong>
            </span>
          </div>

          {/* Recommended Action */}
          <div className="bg-amber-50/80 border border-amber-200 p-3 rounded text-amber-900">
            <h4 className="font-bold text-xs uppercase tracking-wider text-amber-800 mb-1 flex items-center">
              <ShieldCheck className="w-4 h-4 mr-1 text-amber-700" />
              Standard Operating Procedure / Emergency Response
            </h4>
            <p className="text-xs leading-relaxed font-medium">
              {alert.recommendedAction}
            </p>
          </div>

          {/* Contributing Factors */}
          <div>
            <h4 className="font-semibold text-slate-900 text-xs mb-1.5 flex items-center">
              <AlertTriangle className="w-3.5 h-3.5 mr-1 text-purple-600" />
              Observed Atmospheric & Satellite Triggers
            </h4>
            <ul className="space-y-1 pl-4 list-disc text-slate-700 text-xs">
              {alert.factors.map((factor, idx) => (
                <li key={idx}>{factor}</li>
              ))}
            </ul>
          </div>

          {/* Recipient Groups */}
          <div className="border-t border-slate-100 pt-3 text-slate-600">
            <span className="font-semibold text-slate-700">Dispatched Agency Channels: </span>
            <span>{alert.recipientGroup}</span>
          </div>

          {/* Status info */}
          {alert.acknowledgedBy && (
            <div className="bg-slate-50 p-2.5 rounded border border-slate-200 text-[11px] text-slate-600 flex items-center justify-between">
              <span>Acknowledged by: <strong>{alert.acknowledgedBy}</strong></span>
              <span>Time: {new Date(alert.acknowledgedAt || '').toLocaleTimeString()} IST</span>
            </div>
          )}
          {alert.resolvedAt && (
            <div className="bg-emerald-50 p-2.5 rounded border border-emerald-200 text-[11px] text-emerald-800 flex items-center justify-between">
              <span>Status: <strong>Nowcast Threat Cleared</strong></span>
              <span>Time: {new Date(alert.resolvedAt).toLocaleTimeString()} IST</span>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-3 border-t border-slate-100 bg-slate-50 flex items-center justify-between">
          <button
            type="button"
            onClick={() => {
              onViewOnMap(alert.locationId);
              onClose();
            }}
            className="px-3 py-2 bg-purple-900 hover:bg-purple-800 text-white rounded text-xs font-semibold cursor-pointer flex items-center space-x-1.5"
          >
            <MapPin className="w-3.5 h-3.5" />
            <span>View on Risk Map</span>
          </button>

          <div className="flex items-center space-x-2">
            {alert.status === 'ACTIVE' && (
              <button
                type="button"
                onClick={() => onAcknowledge(alert.id)}
                className="px-3 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded text-xs font-semibold cursor-pointer flex items-center space-x-1.5"
              >
                <Check className="w-3.5 h-3.5" />
                <span>Acknowledge</span>
              </button>
            )}

            {alert.status !== 'RESOLVED' && (
              <button
                type="button"
                onClick={() => onResolve(alert.id)}
                className="px-3 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded text-xs font-semibold cursor-pointer flex items-center space-x-1.5"
              >
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>Mark Resolved</span>
              </button>
            )}

            <button
              type="button"
              onClick={onClose}
              className="px-3 py-2 border border-slate-300 hover:bg-white text-slate-700 rounded text-xs font-medium cursor-pointer"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
